# Generated by Django 3.0.5 on 2020-06-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='warehouse',
            field=models.ManyToManyField(to='collection.WareHouse'),
        ),
    ]
