# Generated by Django 3.0.5 on 2020-06-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20200604_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='item',
            field=models.ManyToManyField(to='collection.Item'),
        ),
    ]
