# Generated by Django 3.0.5 on 2020-06-05 07:19

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20200604_2245'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='warehouse',
            managers=[
                ('allitems', django.db.models.manager.Manager()),
            ],
        ),
    ]
