# Generated by Django 3.0.5 on 2020-06-05 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20200605_1304'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='warehouse',
            managers=[
            ],
        ),
    ]
